/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sem56;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Playerselection extends javax.swing.JFrame {

    /**
     * Creates new form Playerselection
     */
    public Playerselection(int table){
        initComponents();
        this.table=table;
    }
    static int table;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter the no of players");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 90, 250, 60);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(280, 110, 120, 22);

        jButton1.setText("Play");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 230, 100, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sem56/New Folder/1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 510, 340);

        setSize(new java.awt.Dimension(525, 387));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a;
        if(table==1){
            a=Integer.parseInt(jTextField1.getText());
            switch(a){
                case 2: EnterAmount ea2=new EnterAmount(a,1);
                        ea2.setVisible(true);
                        this.setVisible(false);
                         break;                   
                case 3:EnterAmount ea3=new EnterAmount(a,1);
                        ea3.setVisible(true);
                        this.setVisible(false);
                         break;
                case 4:EnterAmount ea4=new EnterAmount(a,1);
                        ea4.setVisible(true);
                        this.setVisible(false);
                         break;
                case 5:EnterAmount ea5=new EnterAmount(a,1);
                        ea5.setVisible(true);
                        this.setVisible(false);
                         break;
                case 6:EnterAmount ea6=new EnterAmount(a,1);
                        ea6.setVisible(true);
                        this.setVisible(false);
                         break;
                case 7:EnterAmount ea7=new EnterAmount(a,1);
                        ea7.setVisible(true);
                        this.setVisible(false);
                         break;
                case 8:EnterAmount ea8=new EnterAmount(a,1);
                        ea8.setVisible(true);
                        this.setVisible(false);
                         break;
                case 9:EnterAmount ea9=new EnterAmount(a,1);
                        ea9.setVisible(true);
                        this.setVisible(false);
                         break;         
                default:JOptionPane.showMessageDialog(null, "Enter values between 2 and 9");

            }
        }
        else
        {
            a=Integer.parseInt(jTextField1.getText());
            switch(a){
                case 2: EnterAmount ea2=new EnterAmount(a,2);
                        ea2.setVisible(true);
                        this.setVisible(false);
                         break;                   
                case 3:EnterAmount ea3=new EnterAmount(a,2);
                        ea3.setVisible(true);
                        this.setVisible(false);
                         break;
                case 4:EnterAmount ea4=new EnterAmount(a,2);
                        ea4.setVisible(true);
                        this.setVisible(false);
                         break;
                case 5:EnterAmount ea5=new EnterAmount(a,2);
                        ea5.setVisible(true);
                        this.setVisible(false);
                         break;
                case 6:EnterAmount ea6=new EnterAmount(a,2);
                        ea6.setVisible(true);
                        this.setVisible(false);
                         break;
                case 7:EnterAmount ea7=new EnterAmount(a,2);
                        ea7.setVisible(true);
                        this.setVisible(false);
                         break;
                case 8:EnterAmount ea8=new EnterAmount(a,2);
                        ea8.setVisible(true);
                        this.setVisible(false);
                         break;
                case 9:EnterAmount ea9=new EnterAmount(a,2);
                        ea9.setVisible(true);
                        this.setVisible(false);
                         break;         
                default:JOptionPane.showMessageDialog(null, "Enter values between 2 and 9");

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Playerselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Playerselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Playerselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Playerselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Playerselection(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
